[package]
name = "distribution"
version = "0.1.0"
edition = "2018"

[dependencies]
core-engine = { path = "../core-engine" }
ingest-models = { path = "../ingest-models" }

[[example]]
name = "bot_client"
path = "../../examples/bot_client.rs"


[[bench]]
name = "bench_dispatch"
harness = false

[[bench]]
name = "tick_to_egress"
harness = false
path = "benches/tick_to_egress.rs"

[dev-dependencies]
cefi-ingest = { path = "../cefi-ingest" }
